### ISSUE TITLE
一进来能不能不要先跳出相册授权弹框，点击得时候在弹出

### ISSUE THREAD

**Issue by lzc1022** [iotjin/JhForm#1]

**Comment by lzc1022** [comment]
作者能修改下吗

**Comment by iotjin** [comment]
选择图片使用的是HXPhotoPicker,暂时没有找到开放出来的控制权限的代码。如果你真的介意弹框,你可以使用JhFormCellModel_AddCustumBottomCell 自己写选择图片布局,点击的时候做权限处理,或者改动他的权限判断源代码
