### ISSUE TITLE
网络请求图片回显问题

### ISSUE THREAD

**Issue by cscws** [iotjin/JhForm#10]
Jh_isUseUrlShowPicture 设置为yes ，请求网络图片回显，刷新后会走setData方法，闪退

**Comment by iotjin** [comment]
能否给个demo或者关键代码，我没有重现出来

**Comment by cscws** [comment]
![QQ20200114-111501](https://user-images.githubusercontent.com/9584610/72311359-57540900-36bf-11ea-8373-7639fecad6fe.png)
![QQ20200114-111622](https://user-images.githubusercontent.com/9584610/72311360-58853600-36bf-11ea-98ef-f5aae64b7da7.png)
demo1VC.m 按照这样改。（闪退的问题没复现）。你点击右上角“文字”后，再来回下拉tableview，再点添加图片按钮，会有问题。也不知道是不是我的代码有问题

**Comment by iotjin** [comment]
动态更新iamgeArr是有bug，当有本地图片和URL类型图片动态更新会崩溃，我考虑一下怎么改

**Comment by iotjin** [comment]
我更新了一下代码，你再试试

**Comment by cscws** [comment]
流弊
