### ISSUE TITLE
希望添加可以添加视频的cell

### ISSUE THREAD

**Issue by shengxiaolei** [iotjin/JhForm#11]
你好，框架十分好用，十分感谢。

但cell貌似没有可以添加视频的cell，可以拓展一下吗

**Comment by iotjin** [comment]
JhFormSelectImageCell的oneManager里面可以配置上传图片、视频，现在设置的是只上传图片，你可以自己改一下

**Comment by shengxiaolei** [comment]
图片的cell不能动态控制行高吗?

**Comment by iotjin** [comment]
> 图片的cell不能动态控制行高吗?

已改为高度自适应

**Comment by heliang219** [comment]
需要自己去加videoCell，可以是可以。但是更希望大侠处理好，然后用pod的形式引入，这样封装性更好，也更灵活。

**Comment by iotjin** [comment]
已添加视频选择
