### ISSUE TITLE
能不能增加UIFont这个属性、textView支持竖排吗？

### ISSUE THREAD

**Issue by dslcoding** [iotjin/JhForm#12]
![Jietu20200407-210227](https://user-images.githubusercontent.com/26846337/78672361-1dd41800-7913-11ea-81d4-18a70f7be9cd.jpg) 这个图片上的“添加图片的那个cell在不需要的时候能不能删除”。能不能增加UIFont这个属性、textView支持竖排吗？非常感谢

**Comment by iotjin** [comment]
标题如果不需要，把title设置成@‘’‘’即可，如果你想要修改字体，可以通过Jh_attributedTitle 设置富文本，textView竖排暂不考虑
