### ISSUE TITLE
真机调度偶尔会出现获取不到图片的问题

### ISSUE THREAD

**Issue by dslcoding** [iotjin/JhForm#14]
JhFormCellModel *cell7 = JhFormCellModel_AddImageCell(title, NO);
    cell7.Jh_tipsInfo =@"长按可以调整图片顺序";
    cell7.Jh_titleTextColor = [UIColor redColor];
    [cellArr0 addObjectsFromArray: @[cell3,cell7]];
    JhFormSectionModel *section0 = JhSectionModel_Add(cellArr0);
    [self.Jh_formModelArr addObject:section0];
self.JhClickNavRightItemBlock = ^{
 //这里我已经选择图片了，但是有时候他会是空的.。不知道是怎么回事。
        NSLog(@" 99999选择图片类 - Jh_selectImageArr: %@ ",cell7.Jh_selectImageArr)
    };

**Comment by iotjin** [comment]
你好，你说的问题我没有复现，请问你设备版本是多少，还有你说的有时候是界面不滚动一直点击会复现还是滚动之后再点击图片为空，还是指的什么？可否提供一个能复现问题的小demo？

**Comment by dslcoding** [comment]
在项目中。不太方便。ios13.5.1.。就是添加图片之后。没有滚动。直接点击提交。那个数组会返回空。
