### ISSUE TITLE
选择四张图片，cell没有自适应

### ISSUE THREAD

**Issue by dslcoding** [iotjin/JhForm#15]
![Jietu20200722-202915](https://user-images.githubusercontent.com/26846337/88176621-24846200-cc5a-11ea-90aa-a511d1e1ea46.jpg)（不是“我的”是“空的”，打错字了，不好意思）
选择四张图片，cell没有自适应

**Comment by iotjin** [comment]
> ![Jietu20200722-202915](https://user-images.githubusercontent.com/26846337/88176621-24846200-cc5a-11ea-90aa-a511d1e1ea46.jpg)（不是“我的”是“空的”，打错字了，不好意思）
> 选择四张图片，cell没有自适应

已处理
