### ISSUE TITLE
选择四张图片，cell没有自适应

### ISSUE THREAD

**Issue by dslcoding** [iotjin/JhForm#16]
我已经收到 你更改的邮件，我更新了我的代码，也试你的原代码，都不行，那个效果还没有实现
![Jietu20200804-190936](https://user-images.githubusercontent.com/26846337/89287204-197ff780-d686-11ea-9eca-14c51cc4e862.jpg)

**Comment by iotjin** [comment]
246 替换成  row = data.Jh_maxImageCount>itemLineCount && data.Jh_imageArr.count >= itemLineCount ?2:1; 
再试试？

**Comment by dslcoding** [comment]
可以，你可以更新了。目前，亲测有效。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "iotjin/JhForm"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月5日(星期三) 上午9:23
收件人:&nbsp;"iotjin/JhForm"<JhForm@noreply.github.com&gt;;
抄送:&nbsp;"memefa "<3156693457@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iotjin/JhForm] 选择四张图片，cell没有自适应 (#16)





 
246 替换成  row = data.Jh_maxImageCount&gt;itemLineCount &amp;&amp; data.Jh_imageArr.count &gt;= itemLineCount ?2:1;
 再试试？

**Comment by dslcoding** [comment]
不知道是是怎么回事。非常感谢。
