### ISSUE TITLE
你好 如何添加自定义xib

### ISSUE THREAD

**Issue by co3318co** [iotjin/JhForm#2]

**Comment by co3318co** [comment]
怎么添加自定义的xibcell呢 我弄了半天

**Comment by co3318co** [comment]
想直接把自己的cell添加到轮子里面的表单里面 这边确实靠model 塞数据传过去 新手 望讲解

**Comment by co3318co** [comment]
方便加个qq详细问一下吗

**Comment by iotjin** [comment]
//UITableViewCell 分类
 + (id)Jh_loadFromXib {
 return [[[NSBundle mainBundle] loadNibNamed:NSStringFromClass(self) owner:self options:nil]lastObject];
 }
 自定义的cell名称  *XibCell = [自定义的cell名称 Jh_loadFromXib];
 JhFormCellModel *Cell = JhFormCellModel_AddCustumRightCell(@"xibCell");
 Cell.Jh_custumRightViewBlock = ^(UIView *RightView) {
 [RightView addSubview: XibCell];
 };

现在只有通过自定义右侧或底部view的block 添加自定义的view和xib

**Comment by co3318co** [comment]
射射 我一直想在轮子里面塞个我自己的cell进去 发现一直难搞

**Comment by co3318co** [comment]
能跟新一下轮子🐎 我这边 一直报错 谢谢大神辣！！！！！！！！！！！！！！
