### ISSUE TITLE
自定义view 不显示，是怎么回事

### ISSUE THREAD

**Issue by dslcoding** [iotjin/JhForm#21]
JhFormCellModel *Section1_cell1 = JhFormCellModel_AddCustumALLViewCell(100);
        Section1_cell1.Jh_custumALLViewBlock = ^(UIView * _Nonnull allView) {
            //allView.frame = CGRectMake(0, 0, SCREEN_WIDTH, 100);
            UIButton * imageBtn = [UIButton buttonWithType:UIButtonTypeCustom];
            imageBtn.frame = CGRectMake(0, 0, 100, 100);
            imageBtn.titleLabel.lineBreakMode = 0;//这句话很重要，不加这句话加上换行符也没用
            imageBtn.titleLabel.textAlignment = NSTextAlignmentCenter;
            imageBtn.titleLabel.numberOfLines = 0;
            [imageBtn setTitle:[NSString stringWithFormat:@"+添加图片(可无)"] forState:UIControlStateNormal];
            imageBtn.backgroundColor = [UIColor yellowColor];
            [imageBtn addTarget:self action:@selector(chageBtnImage:) forControlEvents:UIControlEventTouchUpInside];
            self.imageBtn = imageBtn;
            [allView addSubview:imageBtn];
           
            
            UIButton * deleteBtn = [UIButton buttonWithType:UIButtonTypeCustom];
            deleteBtn.frame = CGRectMake(70, 0, 30, 30);
            deleteBtn.hidden = YES;
            [deleteBtn setImage:[UIImage imageNamed:@"compose_picture_add"] forState:UIControlStateNormal];
            deleteBtn.backgroundColor = [UIColor redColor];
            [deleteBtn addTarget:self action:@selector(delebtn) forControlEvents:UIControlEventTouchUpInside];
            [imageBtn addSubview:deleteBtn];
            self.deleteBtn = deleteBtn;
        };

你样例Demo 中显示，但是在我的项目工程中还是不显示。

**Comment by iotjin** [comment]
是不是你用的版本和demo不一样？

**Comment by dslcoding** [comment]
能说个联系方式吗？，我这有个bug需要发给你小视频。

**Comment by dslcoding** [comment]
https://user-images.githubusercontent.com/26846337/118900795-63e81180-b944-11eb-8a1a-6bbca621912c.mp4
你好，你看看这是什么情况。我感觉他好像是重置了。

**Comment by iotjin** [comment]
看着你那个按钮点的时候就不太正常，是不是你哪里把值清掉了，或者你把这块代码发出来我看看

**Comment by dslcoding** [comment]
[JhForm-test.zip](https://github.com/iotjin/JhForm/files/6521282/JhForm-test.zip)
这是原代码，你看一下这是怎么回事。

**Comment by iotjin** [comment]
你添加的按钮的view，应该用个懒加载的view，然后用allview 添加这个bgView

**Comment by dslcoding** [comment]
- (UIView*)autoWidthViewsContainer
{
    if (_autoWidthViewsContainer == nil) {
        _autoWidthViewsContainer = [[UIView alloc]init];
    }
    return _autoWidthViewsContainer;
}
我加了这段代码，还是不行。要不你再调试一下？

**Comment by iotjin** [comment]
你把创建btn的全都放到懒加载里，不要放外面，allView block里只添加self.bgView
