### ISSUE TITLE
VC作为子控制器,tableView的宽不是屏幕宽时,右边按钮图标坐标和右侧箭头重叠了

### ISSUE THREAD

**Issue by bigcoww** [iotjin/JhForm#23]
JhFormTableViewVC *tableViewVC = [[JhFormTableViewVC alloc]init];
    
 tableViewVC.Jh_formTableView.frame = CGRectMake(15, 15, IPHONE_WIDTH-30, 45*6);
 [self addChildViewController:tableViewVC];
 [self.view addSubview:tableViewVC.view];
 [tableViewVC didMoveToParentViewController:self];
    
JhFormCellModel *cell0 = JhFormCellModel_AddRightArrowCell(VSLocalizedString(@"ADD_STAFF_PHOTO"), @"");

这种情况右按钮图片会和右箭头重叠

**Comment by iotjin** [comment]
暂时没考虑这种使用场景，你可以使用自定义cell实现，或者改一下源码
