### ISSUE TITLE
在作为子控制器添加的时候，TableView位置显示位置向下偏移。

### ISSUE THREAD

**Issue by wyggg** [iotjin/JhForm#25]
在作为子控制器添加的时候，TableView位置向下偏移，因为导航高度写为固定的。

JhFormConst.h 第26行
#define Jh_NavHeight (Jh_StatusBarHeight + Jh_ContentNavBarHeight)

JhFormTableViewVC.m 第97行
tableView.frame = CGRectMake(0, Jh_NavHeight, Jh_ScreenWidth, Jh_ScreenHeight-Jh_NavHeight-Jh_BottomSafeHeight);

能否提供接口，修改这个值？
或许可以修改为更灵活的接入方式。

**Comment by iotjin** [comment]
添加子控制器时可以重新设置一下frame
