### ISSUE TITLE
改变cell的高度

### ISSUE THREAD

**Issue by baiRookie** [iotjin/JhForm#5]
重新设置cell的高度,发现cell中的标题已经内容都不是居中显示,比如textView在cell增高时,内容显示无法居中

**Comment by iotjin** [comment]
现在标题和右侧控件默认都不是居中，麻烦你说一下你使用的哪种类型的cell和使用场景，我考虑下是否增加居中展示效果

**Comment by baiRookie** [comment]
我需要改变cell高度，默认是高度是44，设置高度为60后，cell的title以及右侧的视图，比如textview，显示的内容不是居中的，都是偏上显示的，需要将内容视图与cell的y轴方向距离调整为cell的高度减去控件高度再除2，就不会出现这种情况了，但是textview我就没想好怎么搞


发自我的 iPhone

**Comment by iotjin** [comment]
你说的只是JhFormCellTypeInput 类型的cell？

**Comment by baiRookie** [comment]
所有的，你可以尝试将所有的cell类型高度改变，然后设置title，或者其他值，当然，都只有一行，多行我没试过

发自我的 iPhone

**Comment by iotjin** [comment]
哦哦，我知道了，我这边项目没有居中展示的需求，所以项目中是按靠上展示的，我会考虑增加这种展示方式

**Comment by chenchaohui6666** [comment]
确实，这个控件非常好，就是cell标题不居中的问题很麻烦
