### ISSUE TITLE
可以增加选择视频和音频功能吗？

### ISSUE THREAD

**Issue by Zhaoyazhou1996** [iotjin/JhForm#7]
你好，框架十分好用，十分感谢，但是项目需求要可以上传视频和音频，我只是一个刚学iso3个月的小菜鸡，还只能用用别人写好的东西，如果能实现的话，万分感谢！

**Comment by iotjin** [comment]
JhFormSelectImageCell的oneManager里面可以配置上传图片、视频，音频的话就需要你自己实现了

**Comment by Zhaoyazhou1996** [comment]
好的，我研究研究，非常感谢！

**Comment by iotjin** [comment]
已添加视频选择
