### ISSUE TITLE
UIViewController+JhPresentStyle.h 你这个里面重写的方法会造成全局污染的

### ISSUE THREAD

**Issue by 91geek** [iotjin/JhForm#8]
这会导致所有presentInViewController 背景都是黑屏。

**Comment by iotjin** [comment]
你好，这个分类就是全局的，重写系统的方法，目的就是为了全屏弹出，如果不想要这种效果可以删除这个分类。弹出背景黑屏的原因是不是弹出的视图没有设置背景颜色？
