### ISSUE TITLE
最新版本HXPhotoPicker没有兼容？

### ISSUE THREAD

**Issue by 91geek** [iotjin/JhForm#9]
最新版的HXPhotoPicker 没有兼容？兼容的是HXPhotoPicker的哪个版本？

**Comment by iotjin** [comment]
HXPhotoPicker代码的HXPhotoDefine 写的是2.2.4

**Comment by dslcoding** [comment]
你好，能不能把HXPhotoPicker更新到最新版的。谢谢

**Comment by 91geek** [comment]
HXPhotoPicker这个库本身也在用，如果不是最新的，会有冲突。

**Comment by iotjin** [comment]
HXPhotoPicker已更新至v2.4.2版本
